#!/bin/sh

#--------------------------------------------------------------------
# Appearance Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Switch to Dark Mode
    "appearance:dark")
        osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to true'
        echo "${WHITEBOLD}Appearance:${NC} ${GREEN}Dark Mode${NC}"
    ;;

    # Switch to Light Mode
    "appearance:light")
        osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to false'
        echo "${WHITEBOLD}Appearance:${NC} ${GREEN}Light Mode${NC}"
    ;;

    # Toggle between Light and Dark Mode
    "appearance:toggle")
        osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to not dark mode'
        echo "${WHITEBOLD}Appearance:${NC} ${GREEN}Toggled${NC}"
    ;;

esac
