#!/bin/sh

#--------------------------------------------------------------------
# iTerm Utilities
#--------------------------------------------------------------------

case "$fn" in
# Set title to current iTerm tab
	"iterm:tab-title")
	    if [ "$echocommand" == "true" ]; then
	        echo "${GREEN}echo -ne '\033]0;'${GRAY}${firstparameter}${GREEN}'\007'\n\n${NC}"
		fi
		echo -ne '\033]0;'$allParameters'\007'
		echo "Tab title updated"
	;;
esac
