#!/bin/sh

#--------------------------------------------------------------------
# Homebrew Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Update Homebrew and installed packages
    "mas:upgrade")
        echo "Updating Homebrew and its installed packages..."
        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}mas upgrade;\n${NC}"
        fi
        mas upgrade;
    ;;

esac
