#!/bin/sh

#--------------------------------------------------------------------
# Network Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Internet connection speed test
    "speedtest")

        if [ ! -f /usr/local/lib/node_modules/speed-test/cli.js ]; then
            read -r -p "Do you want to install the Speed Test utility? (https://github.com/sindresorhus/fast-cli) (Yes / No)" response
            case $response in
                [yY][eE][sS]|[yY])
                    npm install --global fast-cli
                    ;;
                *)
                    exit
                    ;;
            esac
        else
            echo "Testing internet connection speed..."
            fast
        fi
    ;;


    # Run internet connection Speed Test each 5 minutes
    "speedtest:infinite")

        if [ ! -f /usr/local/lib/node_modules/speed-test/cli.js ]; then
            read -r -p "Do you want to install the Speed Test utility? (https://github.com/sindresorhus/fast-cli) (Yes / No)" response
            case $response in
                [yY][eE][sS]|[yY])
                    npm install --global fast-cli
                    ;;
                *)
                    exit
                    ;;
            esac
        else
            while true
            do
                title="\nTesting internet connection speed - "
                title+=`date '+%Y-%m-%d %H:%M:%S'`
                echo $title
                fast
                sleep 300
            done
        fi
    ;;


    # List of used ports
    "ports")

        echo "Getting list of used ports..."
        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}sudo lsof -iTCP -sTCP:LISTEN -P\n\n${NC}"
        fi
        sudo lsof -iTCP -sTCP:LISTEN -P
    ;;


    # Get local IP address
    "ip:local")

        local_ip=$(ipconfig getifaddr en0)
        if [ $? == 0 ]; then
            if [ "$echocommand" == "true" ]; then
                echo "${GREEN}ipconfig getifaddr en0\n\n${NC}"
            fi
        else
            if [ "$echocommand" == "true" ]; then
                echo "${GREEN}ipconfig getifaddr en1\n\n${NC}"
            fi
            local_ip=$(ipconfig getifaddr en1)
        fi
        echo "Your IP address is:\n${local_ip}"
    ;;


    # Get public IP address
    "ip:public")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}wget http://ipinfo.io/ip -qO -\n\n${NC}"
        fi
        wget http://ipinfo.io/ip -qO -
    ;;

    # Renew DHCP Lease
    "dhcp:renew")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}sudo ipconfig set en0 DHCP -\n\n${NC}"
        fi
        sudo ipconfig set en0 DHCP
    ;;

    # Clear DNS Cache
    "dns:clear")

        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder -\n\n${NC}"
        fi
        sudo dscacheutil -flushcache && sudo killall -HUP mDNSResponder
    ;;


esac
