#!/usr/bin/env bash

#--------------------------------------------------------------------
# Search Utilities
#--------------------------------------------------------------------

case "$fn" in

    # Find files modified in the last N minutes
    "find:recent")

        echo "Searching for files modified in the last "$firstParameter" minutes..."
        if [ "$echocommand" == "true" ]; then
            echo "${GREEN}sudo find / -mmin ${GRAY}${firstParameter}${GREEN} -type f\n\n${NC}"
        fi
        sudo find / -mmin $firstParameter -type f
    ;;

esac
