#!/bin/sh

#--------------------------------------------------------------------
# Volume Utilities
#--------------------------------------------------------------------
if [ "$fn" == "volume" ]; then
    if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
        osascript -e "set volume output volume $firstParameter"
        echo "${WHITEBOLD}Vol:${NC} ${GREEN}${firstParameter}%${NC}"
    else
        echo "${WHITEBOLD}Vol:${NC} ${GREEN}$(osascript -e "output volume of (get volume settings)")% ${NC}"

    fi
elif [ "$fn" == "volume:ismute" ]; then
    echo "${WHITEBOLD}Mute:${NC} ${GREEN}$(osascript -e 'output muted of (get volume settings)')${NC}"
elif [ "$fn" == "volume:mute" ]; then
    osascript -e "set volume output muted true"
    echo "${WHITEBOLD}Mute:${NC} ${GREEN}true${NC}"
elif [ "$fn" == "volume:unmute" ]; then
    osascript -e "set volume output muted false"
    echo "${WHITEBOLD}Mute:${NC} ${GREEN}false${NC}"
fi

