#!/bin/sh

#--------------------------------------------------------------------
# Volume Utilities
#--------------------------------------------------------------------

case "$fn" in
	"volume")
		if [ ! -z "$firstParameter" -a "$firstParameter" != " " ]; then
			osascript -e "set volume output volume $firstParameter"
			echo "${WHITEBOLD}Vol:${NC} ${GREEN}${firstParameter}%${NC}"
		else
			echo "${WHITEBOLD}Vol:${NC} ${GREEN}$(osascript -e "output volume of (get volume settings)")% ${NC}"
		fi
	;;
	
	"volume:ismute")
		echo "${WHITEBOLD}Mute:${NC} ${GREEN}$(osascript -e 'output muted of (get volume settings)')${NC}"
	;;

	"volume:mute")
		osascript -e "set volume output muted true"
		echo "${WHITEBOLD}Mute:${NC} ${GREEN}true${NC}"
	;;

	"volume:unmute")
		osascript -e "set volume output muted false"
		echo "${WHITEBOLD}Mute:${NC} ${GREEN}false${NC}"
	;;
esac
