#!/bin/sh

# Colors
GREEN='\033[0;32m'
LIGHTGREEN='\033[1;32m'
NC='\033[1;37m'
LIGHTBLUE='\033[01;34m'
NC='\033[0m' # No Color

# In directory
PACKAGE_DIRECTORY="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
suggest_current(){
    case "$1" in
        "editor")
            current=$EDITOR
        ;;
        *)
            current=$(which $1)
        ;;
    esac
    if [ -n $current ]; then
        echo $current | pbcopy
        echo "${NC}Press ⌘V to insert current (${current})"
    fi
}

main() {

    echo "${LIGHTBLUE}================================================"
    echo " Mac CLI Installer"
    echo "================================================${NC}\n"

    git clone https://github.com/martinsnygg/mac-cli.git --depth 1 && cd mac-cli

    echo "${LIGHTGREEN}Please enter path to mysql on your local machine:"
    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/Library/bin/mysql"
    suggest_current mysql
    read mysql_path
    if [ ! -z "$mysql_path" -a "$mysql_path" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/Library/bin/mysql#${mysql_path}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    echo "${LIGHTGREEN}Please enter your mysql user:"
    echo "${NC}Press enter without any value to keep default: root"
    read mysql_user
    if [ ! -z "$mysql_user" -a "$mysql_user" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#mysql_user=\"root\"#mysql_user=\"${mysql_user}\"#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    echo "${LIGHTGREEN}Please enter your mysql password:"
    echo "${NC}Press enter without any value to keep default: root"
    echo "${NC}Type none if no password is used"
    read mysql_password
    if [ ! -z "$mysql_password" -a "$mysql_password" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#mysql_password=\"root\"#mysql_password=\"${mysql_password}\"#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    echo "${LIGHTGREEN}Please enter path to the mysql socket on your local machine:"
    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/tmp/mysql/mysql.sock"
    suggest_current mysql.sock
    read mysql_socket
    if [ ! -z "$mysql_socket" -a "$mysql_socket" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/tmp/mysql/mysql.sock#${mysql_socket}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    echo "${LIGHTGREEN}Please enter path to mysqldump on your local machine:"
    echo "${NC}Press enter without any value to keep default: /Applications/MAMP/Library/bin/mysqldump"
    suggest_current mysqldump
    read mysql_dump
    if [ ! -z "$mysql_dump" -a "$mysql_dump" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#/Applications/MAMP/Library/bin/mysqldump#${mysql_dump}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    echo "${LIGHTGREEN}Please enter path to your Dropbox folder:"
    echo "${NC}Press enter without any value to keep default: /Users/$(id -u -n)/Dropbox/"
    read dropbox_path
    if [ ! -z "$dropbox_path" -a "$dropbox_path" != " " ]; then
        LC_CTYPE=C sed -i'' -e "s#/Users/\$(id -u -n)/Dropbox/#${dropbox_path}#g" "$PACKAGE_DIRECTORY/mac-cli/mac"
    fi

    printf "${LIGHTGREEN}"
    read -r -p "Would you like Mac CLI to show you the commands that are run on each mac command? (Yes / No)" response
    case $response in
        [yY][eE][sS]|[yY])
            LC_CTYPE=C sed -i'' -e 's#echocommand="false"#echocommand="true"#g' "$PACKAGE_DIRECTORY/mac-cli/mac"
            ;;
        *)
            ;;
    esac
    printf "${NC}"

    sudo cp "$PACKAGE_DIRECTORY/mac-cli/mac" /usr/local/bin/mac
    sudo cp -r "$PACKAGE_DIRECTORY/mac-cli/mac-cli/" /usr/local/bin/mac-cli
    sudo chmod -R +x /usr/local/bin/mac-cli/*

    if ! [ -x "$(command -v brew)" ]; then
        echo "Installing Homebrew..."
        echo "${GREEN}/usr/bin/ruby -e '\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)'\n${NC}"
        /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    fi

    if ! [ -x "$(command -v git)" ]; then
        echo "Installing Git..."
        echo "${GREEN}brew install git\n${NC}"
        brew install git
	  fi

    if ! [ -x "$(command -v pv)" ]; then
        echo "Installing pv (Pipe Viewer)..."
        echo "${GREEN}brew install pv\n${NC}"
        brew install pv
	  fi

    if ! [ -x "$(command -v wget)" ]; then
        echo "Installing wget..."
        printf "${GREEN}brew install wget\n${NC}"
        brew install wget
	  fi

    if ! brew list | grep -q bash-completion ; then

            echo "Installing bash-completion\n"
            echo "${GREEN}brew install bash-completion\n\n${NC}"
            brew install bash-completion
            echo 'if [ -f $(brew --prefix)/etc/bash_completion ]; then source $(brew --prefix)/etc/bash_completion; fi' >> ~/.bashrc
            echo "Setting up Mac-CLI bash-completion\n"

        if [ -d /usr/local/etc/bash_completion.d/ ]; then
            cp /usr/local/bin/mac-cli/completion/bash_completion /usr/local/etc/bash_completion.d/mac
        fi

    else

        echo "Setting up Mac-CLI bash-completion\n"

        if [ -d $(brew --prefix)/etc/bash_completion.d/ ]; then
            cp /usr/local/bin/mac-cli/completion/bash_completion $(brew --prefix)/etc/bash_completion.d/mac
            echo 'if [ -f $(brew --prefix)/etc/bash_completion ]; then source $(brew --prefix)/etc/bash_completion; fi' >> ~/.bashrc
        fi

    fi

    #
    # Check if fish shell is installed and prompt user to copy fish_completion
    #
    if $(cat /etc/shells | grep -q fish) && [ -d ~/.config/fish ];
    then
	    printf "${LIGHTGREEN}"
	    read -r -p "Would you like to install fish shell suggestions/tab completion? (Yes / No) " response
	    case $response in
		    [yY][eE][sS]|[yY])
			    echo "Setting up Mac-CLI Fish completion"
			    if [ -d ~/.config/fish/completions ];then
				    cp /usr/local/bin/mac-cli/completion/fish_completion ~/.config/fish/completions/mac.fish
			    else
				    mkdir ~/.config/fish/completions && cp /usr/local/bin/mac-cli/completion/fish_completion ~/.config/fish/completions/mac.fish
			    fi
			    ;;
		    *)
			    ;;
	    esac
	    printf "${NC}"
    fi
}

main
