#!/bin/sh

GREEN='\033[0;32m'
NC='\033[0m' # No Color

main() {
  echo "Upgrading Mac CLI..."
	rm /usr/local/bin/mac
	rm -rf /usr/local/bin/mac-cli
	if [ -d ~/Downloads/mac-cli-update/ ]; then
	    rm -rf ~/Downloads/mac-cli-update/
	fi
	mkdir ~/Downloads/mac-cli-update/ && cd ~/Downloads/mac-cli-update/
	sh -c "$(curl -fsSL https://raw.githubusercontent.com/martinsnygg/mac-cli/master/mac-cli/tools/install)" && cd -
	echo "${GREEN}Mac CLI has been updated to the latest version\n${NC}"
}

main