#!/usr/bin/env ruby

require 'commander/import'
require 'terminal-table'
require 'term/ansicolor'
require 'csv'

require 'cupertino'

HighLine.track_eof = false # Fix for built-in Ruby
Signal.trap("INT") {} # Suppress backtrace when exiting command

program :version, Cupertino::VERSION
program :description, 'A command-line interface for the iOS Provisioning Portal'

program :help, 'Author', 'Mattt Thompson <m@mattt.me>'
program :help, 'Website', 'https://github.com/mattt'
program :help_formatter, :compact

default_command :help

require 'cupertino/provisioning_portal'
require 'cupertino/provisioning_portal/commands'
